### PR TITLE
Client auto-reconnect option

### PR DESCRIPTION
**Pull request by Vlaadjka**
Added client option :auto-reconnect. When set to true, client will try to reconnect. More info on eclipse paho auto-reconnect: https://github.com/eclipse/paho.mqtt.java/issues/9

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thanks. It's worth mentioning that this is a non-trivial breaking API change.

**Comment by michaelklishin** [comment]
@Vlaadjka please rebase this against master. I think we will do a release without this change but with #21 and then merge this one and bump major version.

**Comment by michaelklishin** [comment]
This has conflicts and needs rebasing again. @jakubholynet would you be interested in reviewing this? :) I'm happy to make you a collaborator given your recent rate of contributions.

**Comment by jakubholynet** [comment]
@michaelklishin OK, I will have a look

**Comment by michaelklishin** [comment]
@jakubholynet looks like this is ready for a proper review :)

**Comment by jakubholynet** [comment]
Awesome! Im off computer until Wednesday but will have a look ASAP after
that. Thanks, @Vlaadjka!
søn. 11. des. 2016 kl. 21.56 skrev Michael Klishin <notifications@github.com

**Comment by jakubholynet** [comment]
I hope I will manage to check this later today.

**Comment by jakubholynet** [comment]
@michaelklishin Why have you commented that this is a breaking change? I don't think the behaviour - from user's perspective - is different then before. Internally, we replaced `MqttCallback` with `MqttCallbackExtended` but it extends the former so it is backwards-compatible.

I have reviewed it and it looks OK so recommend to merge it. (I don't have the necessary rights to do so.)

**Comment by michaelklishin** [comment]
@jakubholynet because one more callback is now required as far as I can tell. That's not a reason to not merge this, we should just be mindful of it. I've forgotten that Machine Head is not yet 1.0, so this is even less of an issue.

Thank you for the review! I will add you as a collaborator.

**Comment by michaelklishin** [comment]
@Vlaadjka thank you!

**Comment by Vlaadjka** [comment]
Thanks for reviews. :)

**Pull request merged**
